Repository macadmins/jamf-pro-sdk-python, pull requests merged in 2023-10, with the labels that each got.

#15 Honestpuck documentation categories
  docs/reference/models_classic.rst
  src/jamf_pro_sdk/models/classic/categories.py
  tests/models/test_models_classic_categories.py
Labels: enhancement

#17 Documenting Pro API MDM commands.
  docs/reference/models_pro.rst
  docs/user/pro_api.rst
  src/jamf_pro_sdk/clients/pro_api/__init__.py
  src/jamf_pro_sdk/models/pro/computers.py
  src/jamf_pro_sdk/models/pro/mdm.py
Labels: documentation

#20 Advanced Computer Searches
  CHANGELOG.md
  docs/contributors/index.rst
  docs/reference/models_classic.rst
  pyproject.toml
  src/jamf_pro_sdk/clients/classic_api.py
  src/jamf_pro_sdk/models/classic/advanced_computer_searches.py
  src/jamf_pro_sdk/models/classic/categories.py
  src/jamf_pro_sdk/models/classic/computer_groups.py
  src/jamf_pro_sdk/models/classic/criteria.py
  src/jamf_pro_sdk/models/classic/packages.py
Labels: documentation, enhancement
